task:
  name: Anymal
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:4096,${...num_envs}}
    envSpacing: 4.0
    clipObservations: 5.0
    clipActions: 1.0
    plane:
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
    baseInitState:
      pos:
      - 0.0
      - 0.0
      - 0.62
      rot:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      vLinear:
      - 0.0
      - 0.0
      - 0.0
      vAngular:
      - 0.0
      - 0.0
      - 0.0
    randomCommandVelocityRanges:
      linear_x:
      - -2.0
      - 2.0
      linear_y:
      - -1.0
      - 1.0
      yaw:
      - -1.0
      - 1.0
    control:
      stiffness: 85.0
      damping: 2.0
      actionScale: 0.5
      controlFrequencyInv: 1
    defaultJointAngles:
      LF_HAA: 0.03
      LH_HAA: 0.03
      RF_HAA: -0.03
      RH_HAA: -0.03
      LF_HFE: 0.4
      LH_HFE: -0.4
      RF_HFE: 0.4
      RH_HFE: -0.4
      LF_KFE: -0.8
      LH_KFE: 0.8
      RF_KFE: -0.8
      RH_KFE: 0.8
    urdfAsset:
      collapseFixedJoints: true
      fixBaseLink: false
      defaultDofDriveMode: 4
    learn:
      linearVelocityXYRewardScale: 1.0
      angularVelocityZRewardScale: 0.5
      torqueRewardScale: -2.5e-05
      linearVelocityScale: 2.0
      angularVelocityScale: 0.25
      dofPositionScale: 1.0
      dofVelocityScale: 0.05
      episodeLength_s: 50
    viewer:
      refEnv: 0
      pos:
      - 0
      - 0
      - 4
      lookat:
      - 1.0
      - 1
      - 3.3
    enableCameraSensors: false
  sim:
    dt: 0.02
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 4
      num_velocity_iterations: 1
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 100.0
      default_buffer_size_multiplier: 5.0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_collection: 1
  task:
    randomize: false
    randomization_params:
      frequency: 600
      observations:
        range:
        - 0
        - 0.002
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.02
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
          schedule: linear
          schedule_steps: 3000
      actor_params:
        anymal:
          color: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
              schedule: linear
              schedule_steps: 3000
          rigid_shape_properties:
            friction:
              num_buckets: 500
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            restitution:
              range:
              - 0.0
              - 0.7
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
          dof_properties:
            damping:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            stiffness:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              schedule: linear
              schedule_steps: 3000
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
              schedule: linear
              schedule_steps: 3000
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0.0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Anymal,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: ${....multi_gpu}
      ppo: true
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      e_clip: 0.2
      entropy_coef: 0.0
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      truncate_grads: true
      grad_norm: 1.0
      horizon_length: 24
      minibatch_size: 32768
      mini_epochs: 5
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.001
      max_epochs: ${resolve_default:1000,${....max_iterations}}
      save_best_after: 200
      score_to_win: 20000
      save_frequency: 50
      print_stats: true
pbt:
  enabled: false
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
headless: false
